apiVersion: v2
name: retail-store-gitops
description: Retail Store Microservices deployment via Helm & GitOps
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: retail-store-sample-app
    version: "1.3.0"
    repository: "https://aws-containers.github.io/retail-store-sample-app"
